# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages

stages:
  - clone
  - deploy

steps:
  clone:
    title: Cloning main repository...
    type: git-clone
    stage: clone
    arguments:
      repo: https://github.com/codefresh-contrib/kustomize-sample-app.git
      git: github
      revision: master

  deploy:
    title: Deploying to Production using Kustomize...
    type: freestyle
    stage: deploy
    working_directory: ${{clone}}
    arguments:
      image: codefresh/kubectl:1.14.9
      commands:
        - kubectl config use-context anna-sandbox@codefresh-support
        - kubectl apply -k overlays/production
